# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OptimusPlugins < Formula
  desc "Optimus Near earth orbit tracker"
  homepage ""
  version "0.0.1"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.1/optimus-plugins_0.0.1_darwin_amd64.tar.gz"
      sha256 "eea0c7a9d00d76c2a320054c19f63f3980006d8d0dd38919c037ffc3688e1959"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.1/optimus-plugins_0.0.1_darwin_arm64.tar.gz"
      sha256 "d94f32a92431e248e8db5c8810a1954a0bb2bccecb260cbcfce36b3303babd30"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.1/optimus-plugins_0.0.1_linux_amd64.tar.gz"
      sha256 "42f60d73b89b4d500189c4cbba03a60e0683c3a886454e2283f4882fee8f53f9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.1/optimus-plugins_0.0.1_linux_arm64.tar.gz"
      sha256 "b9a2a08bebed8b840bce17cfee83053d9759e514e7debbe8fbb6a51736a906a9"
    end
  end

  def install
    bin.install "optimus-plugins"
  end
end
