# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OptimusPluginsKush < Formula
  desc "Optimus plugins - [Optimus Near earth orbit tracker]"
  homepage ""
  version "0.0.1"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.1/optimus-plugins_0.0.1_darwin_amd64.tar.gz"
      sha256 "3653c7784fdcc6e10d673d6c383b5e432661838007951f8b9e6557e180cf917f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.1/optimus-plugins_0.0.1_darwin_arm64.tar.gz"
      sha256 "ed76a72989587bd12929a91b5f7bc84e2b490295f1d20a45184166f630870368"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.1/optimus-plugins_0.0.1_linux_amd64.tar.gz"
      sha256 "951ee46972e747d12a8622f5b604c48410cf3725a20d5d7980ab47cee3479f0d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.1/optimus-plugins_0.0.1_linux_arm64.tar.gz"
      sha256 "58cb1a939967bef8e7dad4ad8ea1da5751c630ee9d72dcbf505d4dce8fdf5ecf"
    end
  end

  def install
    bin.install Dir["optimus-*"]
  end
end
