# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OptimusPluginsKush < Formula
  desc "Optimus plugins - [Optimus Near earth orbit tracker]"
  homepage ""
  version "0.0.2"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.2/optimus-plugins_0.0.2_darwin_amd64.tar.gz"
      sha256 "a6441324a71c14d184251d795acf97e3c98bd241eee94d543cd9fe83847e17ee"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.2/optimus-plugins_0.0.2_darwin_arm64.tar.gz"
      sha256 "49d3930c1ffc49d530272a8d8deca0bca783bb6638a27158e05d9187f7924990"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.2/optimus-plugins_0.0.2_linux_amd64.tar.gz"
      sha256 "280d93332f0eb090aa1735d0ed6bdbb029dba061356ed4ab56a0cbce8bdb8de3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kushsharma/optimus-plugins/releases/download/v0.0.2/optimus-plugins_0.0.2_linux_arm64.tar.gz"
      sha256 "acb8e396e77ef3b2ae46f32692fbaf8ff5c5da6e75881f48efe4d906822d1ede"
    end
  end

  def install
    bin.install Dir["optimus-*"]
  end
end
